language: node_js
node_js:
- '8.10'
script:
- npm run test
deploy:
  provider: npm
  email: breath103@gmail.com
  skip_cleanup: true
  api_key:
    secure: KGN13w03RbTENzkkUxCBi8ZrzlmbZL7ME+qO27hZOjpeB1f7oXfbZ8n4p8qgf+nc8roqiY7gTkWXVhLrJLl8/2OKFrz8+coBaa9wDAeqyYON+z27eH6FKLI5WIeRhN2oG0rfwMdvbYq8kylINUHEaReC0u8RU1Z7CCZ3N8BCQ28XJkWliThl5Zg8usJlZtVjlxEKbA12x7SVCBCE4RDD+bjkyopdaj/8RIo1WKUsumS/hP/TUWt9jFx8koztY8zUzEVaVJpVvtFzBxhTmv6RbciN5agwwku29J4jiVFvQqgubEn/lmUDGXGI9sGGlVjB2GbxN+kNGEpKPlbKS6+8oE2l3SdFsCx/DVqlYVF3EG+Pzywag9yxdvLDx238Kd9QRg3YVahoT9HYZeV1FbcSOqqjU9RaKqfquiZwrfoYI4i/dGxehD+F7OU7H6fZO8KNf819iRq2vtsCePMSdPK6u8cdxLwllXc5jS20IFv/h7FyKw9n048kZbIsYuR2/fJcAGP2KgzWWJQgDJJGjjhwaF0CTBJmJ6/I6SNYj67UAO/CMtqmd3wJ4P24sCstfA5HBFr9Zw8iqhhm0auh2K5nelSWHEWEDcV+n05LR1OBNHY3xmUo+mqvpDY5pYzE44RWM5awRXb3RhgIFffTjBnTdW9seN7LNYcj5qGNZtFltb4=
  on:
    branch: master
