language: node_js
node_js:
- '6'
script:
- npm run test
deploy:
  provider: npm
  email: breath103@gmail.com
  skip_cleanup: true
  api_key:
    secure: 1yz15HwLUq5gyz3FoFn9eW/mpT4zDslGlCRvwbc++DwUPLJ1PEYipChBfB0poYodhAyvgoOREIOVplEUc2TeJiU2SWT5SlYVhY+fcsSb9KiZJgyO/VheseAhSBWoQH/2zcWMN00SUgIaScamaCzgAb5YBlUAdpKaFk1pUwkdTfS/Qps341AP0Dwbb88qRJz2UghPXjyfZG68f94vnOD+INryGY0qeyhzFzqyA0vZAfKH059+TLY0yhjVOsOMgILlIzMlL4fTXALFVdodgyBGCzgrV4C4kcHfphk3o/9Jt54VV95UWxmrcMNjKxyYrG904zN9NbU2C/PmU04CGE//mT3SpdEnaFmM5A5BEANYfmmQLDh8zJIZ4ezaFkh70Z9cYLAQBXPtBKj+6JT6rCIMPejWF7TjmmtGChBybzR4GVPWlPtmeLI16IoEUXkqmUspHq0X6D+SRlE68INa3COf1oz7euT3VUEUdZfhpvMIhG8rcrzJMCjtsMU6QYUgfguoniIoejBpvuAeBKqeaxz16nJd2FaHDTSgo7KlNfftOMX7RO2t2Gp1cLPAWi4CJ9hVOFl+y/f06frk9ZhXTlR5vjHiKPXMmYHF0rLPdRmw0YJS1NfmkFDbRs0/lE0aCEbenKnP+JFNzg8IZdSiiafPJHaO/g98TJcLj+V7NJUApNI=
  on:
    branch: master
